export default {
  everyText: '每',
  emptyMonths: '每月',
  emptyMonthDays: '每个月的每一天',
  emptyMonthDaysShort: '每月的第几天',
  emptyWeekDays: '每周的每一天',
  emptyWeekDaysShort: '一周中的天',
  emptyHours: '每隔一小时',
  emptyMinutes: '每一分钟',
  emptyMinutesForHourPeriod: '每',
  yearOption: '年',
  monthOption: '月',
  weekOption: '周',
  dayOption: '天',
  hourOption: '小时',
  minuteOption: '分钟',
  rebootOption: '重启',
  prefixPeriod: '每',
  prefixMonths: '在',
  prefixMonthDays: '在',
  prefixWeekDays: '在',
  prefixWeekDaysForMonthAndYearPeriod: '和',
  prefixHours: '的',
  prefixMinutes: ':',
  prefixMinutesForHourPeriod: '的第',
  suffixMinutesForHourPeriod: '分钟',
  errorInvalidCron: '无效的 cron 表达式',
  clearButtonText: '清除',
  weekDays: [
    // Order is important, the index will be used as value
    '周日', // Sunday must always be first, it's "0"
    '周一',
    '周二',
    '周三',
    '周四',
    '周五',
    '周六',
  ],
  months: [
    // Order is important, the index will be used as value
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
  // Order is important, the index will be used as value
  altWeekDays: [
    '周日', // Sunday must always be first, it's "0"
    '周一',
    '周二',
    '周三',
    '周四',
    '周五',
    '周六',
  ],
  // Order is important, the index will be used as value
  altMonths: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
};
